/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OrganizationRouteRouteImport } from './routes/organization/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrganizationCreateRouteRouteImport } from './routes/organization/create/route'
import { Route as coreLayoutRouteRouteImport } from './routes/(core)/_layout/route'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as coreLayoutJobsRouteRouteImport } from './routes/(core)/_layout/jobs/route'
import { Route as coreLayoutDashRouteRouteImport } from './routes/(core)/_layout/dash/route'
import { Route as coreLayoutJobsJobIdRouteImport } from './routes/(core)/_layout/jobs/$jobId'

const OrganizationRouteRoute = OrganizationRouteRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationCreateRouteRoute = OrganizationCreateRouteRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => OrganizationRouteRoute,
} as any)
const coreLayoutRouteRoute = coreLayoutRouteRouteImport.update({
  id: '/(core)/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const coreLayoutJobsRouteRoute = coreLayoutJobsRouteRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => coreLayoutRouteRoute,
} as any)
const coreLayoutDashRouteRoute = coreLayoutDashRouteRouteImport.update({
  id: '/dash',
  path: '/dash',
  getParentRoute: () => coreLayoutRouteRoute,
} as any)
const coreLayoutJobsJobIdRoute = coreLayoutJobsJobIdRouteImport.update({
  id: '/$jobId',
  path: '/$jobId',
  getParentRoute: () => coreLayoutJobsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/organization': typeof OrganizationRouteRouteWithChildren
  '/organization/create': typeof OrganizationCreateRouteRoute
  '/dash': typeof coreLayoutDashRouteRoute
  '/jobs': typeof coreLayoutJobsRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/jobs/$jobId': typeof coreLayoutJobsJobIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/organization': typeof OrganizationRouteRouteWithChildren
  '/organization/create': typeof OrganizationCreateRouteRoute
  '/dash': typeof coreLayoutDashRouteRoute
  '/jobs': typeof coreLayoutJobsRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/jobs/$jobId': typeof coreLayoutJobsJobIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/organization': typeof OrganizationRouteRouteWithChildren
  '/(core)/_layout': typeof coreLayoutRouteRouteWithChildren
  '/organization/create': typeof OrganizationCreateRouteRoute
  '/(core)/_layout/dash': typeof coreLayoutDashRouteRoute
  '/(core)/_layout/jobs': typeof coreLayoutJobsRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/(core)/_layout/jobs/$jobId': typeof coreLayoutJobsJobIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/organization'
    | '/organization/create'
    | '/dash'
    | '/jobs'
    | '/api/auth/$'
    | '/jobs/$jobId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/organization'
    | '/organization/create'
    | '/dash'
    | '/jobs'
    | '/api/auth/$'
    | '/jobs/$jobId'
  id:
    | '__root__'
    | '/'
    | '/organization'
    | '/(core)/_layout'
    | '/organization/create'
    | '/(core)/_layout/dash'
    | '/(core)/_layout/jobs'
    | '/api/auth/$'
    | '/(core)/_layout/jobs/$jobId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OrganizationRouteRoute: typeof OrganizationRouteRouteWithChildren
  coreLayoutRouteRoute: typeof coreLayoutRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/organization': {
      id: '/organization'
      path: '/organization'
      fullPath: '/organization'
      preLoaderRoute: typeof OrganizationRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organization/create': {
      id: '/organization/create'
      path: '/create'
      fullPath: '/organization/create'
      preLoaderRoute: typeof OrganizationCreateRouteRouteImport
      parentRoute: typeof OrganizationRouteRoute
    }
    '/(core)/_layout': {
      id: '/(core)/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof coreLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(core)/_layout/jobs': {
      id: '/(core)/_layout/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof coreLayoutJobsRouteRouteImport
      parentRoute: typeof coreLayoutRouteRoute
    }
    '/(core)/_layout/dash': {
      id: '/(core)/_layout/dash'
      path: '/dash'
      fullPath: '/dash'
      preLoaderRoute: typeof coreLayoutDashRouteRouteImport
      parentRoute: typeof coreLayoutRouteRoute
    }
    '/(core)/_layout/jobs/$jobId': {
      id: '/(core)/_layout/jobs/$jobId'
      path: '/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof coreLayoutJobsJobIdRouteImport
      parentRoute: typeof coreLayoutJobsRouteRoute
    }
  }
}

interface OrganizationRouteRouteChildren {
  OrganizationCreateRouteRoute: typeof OrganizationCreateRouteRoute
}

const OrganizationRouteRouteChildren: OrganizationRouteRouteChildren = {
  OrganizationCreateRouteRoute: OrganizationCreateRouteRoute,
}

const OrganizationRouteRouteWithChildren =
  OrganizationRouteRoute._addFileChildren(OrganizationRouteRouteChildren)

interface coreLayoutJobsRouteRouteChildren {
  coreLayoutJobsJobIdRoute: typeof coreLayoutJobsJobIdRoute
}

const coreLayoutJobsRouteRouteChildren: coreLayoutJobsRouteRouteChildren = {
  coreLayoutJobsJobIdRoute: coreLayoutJobsJobIdRoute,
}

const coreLayoutJobsRouteRouteWithChildren =
  coreLayoutJobsRouteRoute._addFileChildren(coreLayoutJobsRouteRouteChildren)

interface coreLayoutRouteRouteChildren {
  coreLayoutDashRouteRoute: typeof coreLayoutDashRouteRoute
  coreLayoutJobsRouteRoute: typeof coreLayoutJobsRouteRouteWithChildren
}

const coreLayoutRouteRouteChildren: coreLayoutRouteRouteChildren = {
  coreLayoutDashRouteRoute: coreLayoutDashRouteRoute,
  coreLayoutJobsRouteRoute: coreLayoutJobsRouteRouteWithChildren,
}

const coreLayoutRouteRouteWithChildren = coreLayoutRouteRoute._addFileChildren(
  coreLayoutRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OrganizationRouteRoute: OrganizationRouteRouteWithChildren,
  coreLayoutRouteRoute: coreLayoutRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
