/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as applicationLayoutRouteRouteImport } from './routes/(application)/_layout/route'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as applicationLayoutDashRouteRouteImport } from './routes/(application)/_layout/dash/route'
import { Route as applicationLayoutJobsJobIdRouteImport } from './routes/(application)/_layout/jobs/$jobId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const applicationLayoutRouteRoute = applicationLayoutRouteRouteImport.update({
  id: '/(application)/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const applicationLayoutDashRouteRoute =
  applicationLayoutDashRouteRouteImport.update({
    id: '/dash',
    path: '/dash',
    getParentRoute: () => applicationLayoutRouteRoute,
  } as any)
const applicationLayoutJobsJobIdRoute =
  applicationLayoutJobsJobIdRouteImport.update({
    id: '/jobs/$jobId',
    path: '/jobs/$jobId',
    getParentRoute: () => applicationLayoutRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dash': typeof applicationLayoutDashRouteRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/jobs/$jobId': typeof applicationLayoutJobsJobIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dash': typeof applicationLayoutDashRouteRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/jobs/$jobId': typeof applicationLayoutJobsJobIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(application)/_layout': typeof applicationLayoutRouteRouteWithChildren
  '/(application)/_layout/dash': typeof applicationLayoutDashRouteRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/(application)/_layout/jobs/$jobId': typeof applicationLayoutJobsJobIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dash' | '/api/auth/$' | '/jobs/$jobId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dash' | '/api/auth/$' | '/jobs/$jobId'
  id:
    | '__root__'
    | '/'
    | '/(application)/_layout'
    | '/(application)/_layout/dash'
    | '/api/auth/$'
    | '/(application)/_layout/jobs/$jobId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  applicationLayoutRouteRoute: typeof applicationLayoutRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(application)/_layout': {
      id: '/(application)/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof applicationLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(application)/_layout/dash': {
      id: '/(application)/_layout/dash'
      path: '/dash'
      fullPath: '/dash'
      preLoaderRoute: typeof applicationLayoutDashRouteRouteImport
      parentRoute: typeof applicationLayoutRouteRoute
    }
    '/(application)/_layout/jobs/$jobId': {
      id: '/(application)/_layout/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof applicationLayoutJobsJobIdRouteImport
      parentRoute: typeof applicationLayoutRouteRoute
    }
  }
}

interface applicationLayoutRouteRouteChildren {
  applicationLayoutDashRouteRoute: typeof applicationLayoutDashRouteRoute
  applicationLayoutJobsJobIdRoute: typeof applicationLayoutJobsJobIdRoute
}

const applicationLayoutRouteRouteChildren: applicationLayoutRouteRouteChildren =
  {
    applicationLayoutDashRouteRoute: applicationLayoutDashRouteRoute,
    applicationLayoutJobsJobIdRoute: applicationLayoutJobsJobIdRoute,
  }

const applicationLayoutRouteRouteWithChildren =
  applicationLayoutRouteRoute._addFileChildren(
    applicationLayoutRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  applicationLayoutRouteRoute: applicationLayoutRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
