/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OrganizationRouteRouteImport } from './routes/organization/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrganizationManageRouteRouteImport } from './routes/organization/manage/route'
import { Route as OrganizationCreateRouteRouteImport } from './routes/organization/create/route'
import { Route as SlugLayoutRouteRouteImport } from './routes/$slug/_layout/route'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as SlugLayoutJobsRouteRouteImport } from './routes/$slug/_layout/jobs/route'
import { Route as SlugLayoutDashRouteRouteImport } from './routes/$slug/_layout/dash/route'
import { Route as SlugLayoutJobsJobIdRouteImport } from './routes/$slug/_layout/jobs/$jobId'

const OrganizationRouteRoute = OrganizationRouteRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationManageRouteRoute = OrganizationManageRouteRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => OrganizationRouteRoute,
} as any)
const OrganizationCreateRouteRoute = OrganizationCreateRouteRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => OrganizationRouteRoute,
} as any)
const SlugLayoutRouteRoute = SlugLayoutRouteRouteImport.update({
  id: '/$slug/_layout',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugLayoutJobsRouteRoute = SlugLayoutJobsRouteRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => SlugLayoutRouteRoute,
} as any)
const SlugLayoutDashRouteRoute = SlugLayoutDashRouteRouteImport.update({
  id: '/dash',
  path: '/dash',
  getParentRoute: () => SlugLayoutRouteRoute,
} as any)
const SlugLayoutJobsJobIdRoute = SlugLayoutJobsJobIdRouteImport.update({
  id: '/$jobId',
  path: '/$jobId',
  getParentRoute: () => SlugLayoutJobsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/organization': typeof OrganizationRouteRouteWithChildren
  '/$slug': typeof SlugLayoutRouteRouteWithChildren
  '/organization/create': typeof OrganizationCreateRouteRoute
  '/organization/manage': typeof OrganizationManageRouteRoute
  '/$slug/dash': typeof SlugLayoutDashRouteRoute
  '/$slug/jobs': typeof SlugLayoutJobsRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/$slug/jobs/$jobId': typeof SlugLayoutJobsJobIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/organization': typeof OrganizationRouteRouteWithChildren
  '/$slug': typeof SlugLayoutRouteRouteWithChildren
  '/organization/create': typeof OrganizationCreateRouteRoute
  '/organization/manage': typeof OrganizationManageRouteRoute
  '/$slug/dash': typeof SlugLayoutDashRouteRoute
  '/$slug/jobs': typeof SlugLayoutJobsRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/$slug/jobs/$jobId': typeof SlugLayoutJobsJobIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/organization': typeof OrganizationRouteRouteWithChildren
  '/$slug/_layout': typeof SlugLayoutRouteRouteWithChildren
  '/organization/create': typeof OrganizationCreateRouteRoute
  '/organization/manage': typeof OrganizationManageRouteRoute
  '/$slug/_layout/dash': typeof SlugLayoutDashRouteRoute
  '/$slug/_layout/jobs': typeof SlugLayoutJobsRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/$slug/_layout/jobs/$jobId': typeof SlugLayoutJobsJobIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/organization'
    | '/$slug'
    | '/organization/create'
    | '/organization/manage'
    | '/$slug/dash'
    | '/$slug/jobs'
    | '/api/auth/$'
    | '/$slug/jobs/$jobId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/organization'
    | '/$slug'
    | '/organization/create'
    | '/organization/manage'
    | '/$slug/dash'
    | '/$slug/jobs'
    | '/api/auth/$'
    | '/$slug/jobs/$jobId'
  id:
    | '__root__'
    | '/'
    | '/organization'
    | '/$slug/_layout'
    | '/organization/create'
    | '/organization/manage'
    | '/$slug/_layout/dash'
    | '/$slug/_layout/jobs'
    | '/api/auth/$'
    | '/$slug/_layout/jobs/$jobId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OrganizationRouteRoute: typeof OrganizationRouteRouteWithChildren
  SlugLayoutRouteRoute: typeof SlugLayoutRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/organization': {
      id: '/organization'
      path: '/organization'
      fullPath: '/organization'
      preLoaderRoute: typeof OrganizationRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organization/manage': {
      id: '/organization/manage'
      path: '/manage'
      fullPath: '/organization/manage'
      preLoaderRoute: typeof OrganizationManageRouteRouteImport
      parentRoute: typeof OrganizationRouteRoute
    }
    '/organization/create': {
      id: '/organization/create'
      path: '/create'
      fullPath: '/organization/create'
      preLoaderRoute: typeof OrganizationCreateRouteRouteImport
      parentRoute: typeof OrganizationRouteRoute
    }
    '/$slug/_layout': {
      id: '/$slug/_layout'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/_layout/jobs': {
      id: '/$slug/_layout/jobs'
      path: '/jobs'
      fullPath: '/$slug/jobs'
      preLoaderRoute: typeof SlugLayoutJobsRouteRouteImport
      parentRoute: typeof SlugLayoutRouteRoute
    }
    '/$slug/_layout/dash': {
      id: '/$slug/_layout/dash'
      path: '/dash'
      fullPath: '/$slug/dash'
      preLoaderRoute: typeof SlugLayoutDashRouteRouteImport
      parentRoute: typeof SlugLayoutRouteRoute
    }
    '/$slug/_layout/jobs/$jobId': {
      id: '/$slug/_layout/jobs/$jobId'
      path: '/$jobId'
      fullPath: '/$slug/jobs/$jobId'
      preLoaderRoute: typeof SlugLayoutJobsJobIdRouteImport
      parentRoute: typeof SlugLayoutJobsRouteRoute
    }
  }
}

interface OrganizationRouteRouteChildren {
  OrganizationCreateRouteRoute: typeof OrganizationCreateRouteRoute
  OrganizationManageRouteRoute: typeof OrganizationManageRouteRoute
}

const OrganizationRouteRouteChildren: OrganizationRouteRouteChildren = {
  OrganizationCreateRouteRoute: OrganizationCreateRouteRoute,
  OrganizationManageRouteRoute: OrganizationManageRouteRoute,
}

const OrganizationRouteRouteWithChildren =
  OrganizationRouteRoute._addFileChildren(OrganizationRouteRouteChildren)

interface SlugLayoutJobsRouteRouteChildren {
  SlugLayoutJobsJobIdRoute: typeof SlugLayoutJobsJobIdRoute
}

const SlugLayoutJobsRouteRouteChildren: SlugLayoutJobsRouteRouteChildren = {
  SlugLayoutJobsJobIdRoute: SlugLayoutJobsJobIdRoute,
}

const SlugLayoutJobsRouteRouteWithChildren =
  SlugLayoutJobsRouteRoute._addFileChildren(SlugLayoutJobsRouteRouteChildren)

interface SlugLayoutRouteRouteChildren {
  SlugLayoutDashRouteRoute: typeof SlugLayoutDashRouteRoute
  SlugLayoutJobsRouteRoute: typeof SlugLayoutJobsRouteRouteWithChildren
}

const SlugLayoutRouteRouteChildren: SlugLayoutRouteRouteChildren = {
  SlugLayoutDashRouteRoute: SlugLayoutDashRouteRoute,
  SlugLayoutJobsRouteRoute: SlugLayoutJobsRouteRouteWithChildren,
}

const SlugLayoutRouteRouteWithChildren = SlugLayoutRouteRoute._addFileChildren(
  SlugLayoutRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OrganizationRouteRoute: OrganizationRouteRouteWithChildren,
  SlugLayoutRouteRoute: SlugLayoutRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
