import { Metadata } from "next"
import { Button } from "@/components/ui/button";
import { Loader2 } from "lucide-react";
import { Settings } from "lucide-react";
import { auth } from "@/lib/auth";
import { headers } from "next/headers";
import { redirect } from "next/navigation";
import { Navbar } from "@/components/navbar-2";

export const metadata: Metadata = {
    title: "Loading",
    description: "Generated by create next app",
};

export default async function Loading() {
    const session = await auth.api.getSession({
      headers: await headers()
    })
    if(!session?.user) { redirect('/auth') }
    return (
      <>
      <Navbar session={session} />
      <div className="w-full h-full items-center flex flex-col justify-center mt-36">
        <Loader2 className="size-8 animate-spin text-black" />
        </div>
      </>
    );
  }
  