import { Metadata } from "next"
import { Button } from "@/components/ui/button";
import { Loader2 } from "lucide-react";

export const metadata: Metadata = {
    title: "Loading",
    description: "Generated by create next app",
};

export default function Loading() {
    return (
        <> 
        <div className="flex justify-between items-center w-full">
        <h1 className="font-medium text-3xl text-white tracking-tight">Categories</h1>
        <Button disabled variant={"outline"} className="font-medium border border-dashed px-4 bg-theme rounded-none">
        Create Category
        </Button>
        </div>
        <div className="w-full h-full items-center flex flex-col justify-center">
        <Loader2 className="size-8 animate-spin text-white" />
        </div>
      </>
    )
}