/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ViewIndexRouteImport } from './routes/view/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as ViewSlugRouteRouteImport } from './routes/view/$slug/route'
import { Route as SlugLayoutRouteRouteImport } from './routes/$slug/_layout/route'
import { Route as ViewSlugIndexRouteImport } from './routes/view/$slug/index'
import { Route as SlugLayoutIndexRouteImport } from './routes/$slug/_layout/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as SlugLayoutTeamRouteRouteImport } from './routes/$slug/_layout/team/route'
import { Route as SlugLayoutOrganizationRouteRouteImport } from './routes/$slug/_layout/organization/route'
import { Route as SlugLayoutJobsRouteRouteImport } from './routes/$slug/_layout/jobs/route'
import { Route as SlugLayoutCategoriesRouteRouteImport } from './routes/$slug/_layout/categories/route'
import { Route as SlugLayoutBillingRouteRouteImport } from './routes/$slug/_layout/billing/route'
import { Route as ViewSlugJobIdIndexRouteImport } from './routes/view/$slug/$jobId/index'
import { Route as SlugLayoutJobsIndexRouteImport } from './routes/$slug/_layout/jobs/index'
import { Route as SlugLayoutHiringStagesIndexRouteImport } from './routes/$slug/_layout/hiring-stages/index'
import { Route as SlugLayoutCandidatesIndexRouteImport } from './routes/$slug/_layout/candidates/index'
import { Route as SlugLayoutJobsJobIdRouteRouteImport } from './routes/$slug/_layout/jobs/$jobId/route'
import { Route as SlugLayoutCandidatesJobIdRouteRouteImport } from './routes/$slug/_layout/candidates/$jobId/route'
import { Route as SlugLayoutCandidatesJobIdIndexRouteImport } from './routes/$slug/_layout/candidates/$jobId/index'
import { Route as SlugLayoutCandidatesJobIdCandidateIdRouteImport } from './routes/$slug/_layout/candidates/$jobId/$candidateId'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ViewIndexRoute = ViewIndexRouteImport.update({
  id: '/view/',
  path: '/view/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const ViewSlugRouteRoute = ViewSlugRouteRouteImport.update({
  id: '/view/$slug',
  path: '/view/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugLayoutRouteRoute = SlugLayoutRouteRouteImport.update({
  id: '/$slug/_layout',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ViewSlugIndexRoute = ViewSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ViewSlugRouteRoute,
} as any)
const SlugLayoutIndexRoute = SlugLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SlugLayoutRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugLayoutTeamRouteRoute = SlugLayoutTeamRouteRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => SlugLayoutRouteRoute,
} as any)
const SlugLayoutOrganizationRouteRoute =
  SlugLayoutOrganizationRouteRouteImport.update({
    id: '/organization',
    path: '/organization',
    getParentRoute: () => SlugLayoutRouteRoute,
  } as any)
const SlugLayoutJobsRouteRoute = SlugLayoutJobsRouteRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => SlugLayoutRouteRoute,
} as any)
const SlugLayoutCategoriesRouteRoute =
  SlugLayoutCategoriesRouteRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => SlugLayoutRouteRoute,
  } as any)
const SlugLayoutBillingRouteRoute = SlugLayoutBillingRouteRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => SlugLayoutRouteRoute,
} as any)
const ViewSlugJobIdIndexRoute = ViewSlugJobIdIndexRouteImport.update({
  id: '/$jobId/',
  path: '/$jobId/',
  getParentRoute: () => ViewSlugRouteRoute,
} as any)
const SlugLayoutJobsIndexRoute = SlugLayoutJobsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SlugLayoutJobsRouteRoute,
} as any)
const SlugLayoutHiringStagesIndexRoute =
  SlugLayoutHiringStagesIndexRouteImport.update({
    id: '/hiring-stages/',
    path: '/hiring-stages/',
    getParentRoute: () => SlugLayoutRouteRoute,
  } as any)
const SlugLayoutCandidatesIndexRoute =
  SlugLayoutCandidatesIndexRouteImport.update({
    id: '/candidates/',
    path: '/candidates/',
    getParentRoute: () => SlugLayoutRouteRoute,
  } as any)
const SlugLayoutJobsJobIdRouteRoute =
  SlugLayoutJobsJobIdRouteRouteImport.update({
    id: '/$jobId',
    path: '/$jobId',
    getParentRoute: () => SlugLayoutJobsRouteRoute,
  } as any)
const SlugLayoutCandidatesJobIdRouteRoute =
  SlugLayoutCandidatesJobIdRouteRouteImport.update({
    id: '/candidates/$jobId',
    path: '/candidates/$jobId',
    getParentRoute: () => SlugLayoutRouteRoute,
  } as any)
const SlugLayoutCandidatesJobIdIndexRoute =
  SlugLayoutCandidatesJobIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => SlugLayoutCandidatesJobIdRouteRoute,
  } as any)
const SlugLayoutCandidatesJobIdCandidateIdRoute =
  SlugLayoutCandidatesJobIdCandidateIdRouteImport.update({
    id: '/$candidateId',
    path: '/$candidateId',
    getParentRoute: () => SlugLayoutCandidatesJobIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/$slug': typeof SlugLayoutRouteRouteWithChildren
  '/view/$slug': typeof ViewSlugRouteRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/view/': typeof ViewIndexRoute
  '/$slug/billing': typeof SlugLayoutBillingRouteRoute
  '/$slug/categories': typeof SlugLayoutCategoriesRouteRoute
  '/$slug/jobs': typeof SlugLayoutJobsRouteRouteWithChildren
  '/$slug/organization': typeof SlugLayoutOrganizationRouteRoute
  '/$slug/team': typeof SlugLayoutTeamRouteRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/$slug/': typeof SlugLayoutIndexRoute
  '/view/$slug/': typeof ViewSlugIndexRoute
  '/$slug/candidates/$jobId': typeof SlugLayoutCandidatesJobIdRouteRouteWithChildren
  '/$slug/jobs/$jobId': typeof SlugLayoutJobsJobIdRouteRoute
  '/$slug/candidates/': typeof SlugLayoutCandidatesIndexRoute
  '/$slug/hiring-stages/': typeof SlugLayoutHiringStagesIndexRoute
  '/$slug/jobs/': typeof SlugLayoutJobsIndexRoute
  '/view/$slug/$jobId/': typeof ViewSlugJobIdIndexRoute
  '/$slug/candidates/$jobId/$candidateId': typeof SlugLayoutCandidatesJobIdCandidateIdRoute
  '/$slug/candidates/$jobId/': typeof SlugLayoutCandidatesJobIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/view': typeof ViewIndexRoute
  '/$slug/billing': typeof SlugLayoutBillingRouteRoute
  '/$slug/categories': typeof SlugLayoutCategoriesRouteRoute
  '/$slug/organization': typeof SlugLayoutOrganizationRouteRoute
  '/$slug/team': typeof SlugLayoutTeamRouteRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/$slug': typeof SlugLayoutIndexRoute
  '/view/$slug': typeof ViewSlugIndexRoute
  '/$slug/jobs/$jobId': typeof SlugLayoutJobsJobIdRouteRoute
  '/$slug/candidates': typeof SlugLayoutCandidatesIndexRoute
  '/$slug/hiring-stages': typeof SlugLayoutHiringStagesIndexRoute
  '/$slug/jobs': typeof SlugLayoutJobsIndexRoute
  '/view/$slug/$jobId': typeof ViewSlugJobIdIndexRoute
  '/$slug/candidates/$jobId/$candidateId': typeof SlugLayoutCandidatesJobIdCandidateIdRoute
  '/$slug/candidates/$jobId': typeof SlugLayoutCandidatesJobIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/$slug/_layout': typeof SlugLayoutRouteRouteWithChildren
  '/view/$slug': typeof ViewSlugRouteRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/view/': typeof ViewIndexRoute
  '/$slug/_layout/billing': typeof SlugLayoutBillingRouteRoute
  '/$slug/_layout/categories': typeof SlugLayoutCategoriesRouteRoute
  '/$slug/_layout/jobs': typeof SlugLayoutJobsRouteRouteWithChildren
  '/$slug/_layout/organization': typeof SlugLayoutOrganizationRouteRoute
  '/$slug/_layout/team': typeof SlugLayoutTeamRouteRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/$slug/_layout/': typeof SlugLayoutIndexRoute
  '/view/$slug/': typeof ViewSlugIndexRoute
  '/$slug/_layout/candidates/$jobId': typeof SlugLayoutCandidatesJobIdRouteRouteWithChildren
  '/$slug/_layout/jobs/$jobId': typeof SlugLayoutJobsJobIdRouteRoute
  '/$slug/_layout/candidates/': typeof SlugLayoutCandidatesIndexRoute
  '/$slug/_layout/hiring-stages/': typeof SlugLayoutHiringStagesIndexRoute
  '/$slug/_layout/jobs/': typeof SlugLayoutJobsIndexRoute
  '/view/$slug/$jobId/': typeof ViewSlugJobIdIndexRoute
  '/$slug/_layout/candidates/$jobId/$candidateId': typeof SlugLayoutCandidatesJobIdCandidateIdRoute
  '/$slug/_layout/candidates/$jobId/': typeof SlugLayoutCandidatesJobIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/$slug'
    | '/view/$slug'
    | '/dashboard/'
    | '/view/'
    | '/$slug/billing'
    | '/$slug/categories'
    | '/$slug/jobs'
    | '/$slug/organization'
    | '/$slug/team'
    | '/api/auth/$'
    | '/$slug/'
    | '/view/$slug/'
    | '/$slug/candidates/$jobId'
    | '/$slug/jobs/$jobId'
    | '/$slug/candidates/'
    | '/$slug/hiring-stages/'
    | '/$slug/jobs/'
    | '/view/$slug/$jobId/'
    | '/$slug/candidates/$jobId/$candidateId'
    | '/$slug/candidates/$jobId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/view'
    | '/$slug/billing'
    | '/$slug/categories'
    | '/$slug/organization'
    | '/$slug/team'
    | '/api/auth/$'
    | '/$slug'
    | '/view/$slug'
    | '/$slug/jobs/$jobId'
    | '/$slug/candidates'
    | '/$slug/hiring-stages'
    | '/$slug/jobs'
    | '/view/$slug/$jobId'
    | '/$slug/candidates/$jobId/$candidateId'
    | '/$slug/candidates/$jobId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/$slug/_layout'
    | '/view/$slug'
    | '/dashboard/'
    | '/view/'
    | '/$slug/_layout/billing'
    | '/$slug/_layout/categories'
    | '/$slug/_layout/jobs'
    | '/$slug/_layout/organization'
    | '/$slug/_layout/team'
    | '/api/auth/$'
    | '/$slug/_layout/'
    | '/view/$slug/'
    | '/$slug/_layout/candidates/$jobId'
    | '/$slug/_layout/jobs/$jobId'
    | '/$slug/_layout/candidates/'
    | '/$slug/_layout/hiring-stages/'
    | '/$slug/_layout/jobs/'
    | '/view/$slug/$jobId/'
    | '/$slug/_layout/candidates/$jobId/$candidateId'
    | '/$slug/_layout/candidates/$jobId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  SlugLayoutRouteRoute: typeof SlugLayoutRouteRouteWithChildren
  ViewSlugRouteRoute: typeof ViewSlugRouteRouteWithChildren
  ViewIndexRoute: typeof ViewIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/view/': {
      id: '/view/'
      path: '/view'
      fullPath: '/view/'
      preLoaderRoute: typeof ViewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/view/$slug': {
      id: '/view/$slug'
      path: '/view/$slug'
      fullPath: '/view/$slug'
      preLoaderRoute: typeof ViewSlugRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/_layout': {
      id: '/$slug/_layout'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/view/$slug/': {
      id: '/view/$slug/'
      path: '/'
      fullPath: '/view/$slug/'
      preLoaderRoute: typeof ViewSlugIndexRouteImport
      parentRoute: typeof ViewSlugRouteRoute
    }
    '/$slug/_layout/': {
      id: '/$slug/_layout/'
      path: '/'
      fullPath: '/$slug/'
      preLoaderRoute: typeof SlugLayoutIndexRouteImport
      parentRoute: typeof SlugLayoutRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/_layout/team': {
      id: '/$slug/_layout/team'
      path: '/team'
      fullPath: '/$slug/team'
      preLoaderRoute: typeof SlugLayoutTeamRouteRouteImport
      parentRoute: typeof SlugLayoutRouteRoute
    }
    '/$slug/_layout/organization': {
      id: '/$slug/_layout/organization'
      path: '/organization'
      fullPath: '/$slug/organization'
      preLoaderRoute: typeof SlugLayoutOrganizationRouteRouteImport
      parentRoute: typeof SlugLayoutRouteRoute
    }
    '/$slug/_layout/jobs': {
      id: '/$slug/_layout/jobs'
      path: '/jobs'
      fullPath: '/$slug/jobs'
      preLoaderRoute: typeof SlugLayoutJobsRouteRouteImport
      parentRoute: typeof SlugLayoutRouteRoute
    }
    '/$slug/_layout/categories': {
      id: '/$slug/_layout/categories'
      path: '/categories'
      fullPath: '/$slug/categories'
      preLoaderRoute: typeof SlugLayoutCategoriesRouteRouteImport
      parentRoute: typeof SlugLayoutRouteRoute
    }
    '/$slug/_layout/billing': {
      id: '/$slug/_layout/billing'
      path: '/billing'
      fullPath: '/$slug/billing'
      preLoaderRoute: typeof SlugLayoutBillingRouteRouteImport
      parentRoute: typeof SlugLayoutRouteRoute
    }
    '/view/$slug/$jobId/': {
      id: '/view/$slug/$jobId/'
      path: '/$jobId'
      fullPath: '/view/$slug/$jobId/'
      preLoaderRoute: typeof ViewSlugJobIdIndexRouteImport
      parentRoute: typeof ViewSlugRouteRoute
    }
    '/$slug/_layout/jobs/': {
      id: '/$slug/_layout/jobs/'
      path: '/'
      fullPath: '/$slug/jobs/'
      preLoaderRoute: typeof SlugLayoutJobsIndexRouteImport
      parentRoute: typeof SlugLayoutJobsRouteRoute
    }
    '/$slug/_layout/hiring-stages/': {
      id: '/$slug/_layout/hiring-stages/'
      path: '/hiring-stages'
      fullPath: '/$slug/hiring-stages/'
      preLoaderRoute: typeof SlugLayoutHiringStagesIndexRouteImport
      parentRoute: typeof SlugLayoutRouteRoute
    }
    '/$slug/_layout/candidates/': {
      id: '/$slug/_layout/candidates/'
      path: '/candidates'
      fullPath: '/$slug/candidates/'
      preLoaderRoute: typeof SlugLayoutCandidatesIndexRouteImport
      parentRoute: typeof SlugLayoutRouteRoute
    }
    '/$slug/_layout/jobs/$jobId': {
      id: '/$slug/_layout/jobs/$jobId'
      path: '/$jobId'
      fullPath: '/$slug/jobs/$jobId'
      preLoaderRoute: typeof SlugLayoutJobsJobIdRouteRouteImport
      parentRoute: typeof SlugLayoutJobsRouteRoute
    }
    '/$slug/_layout/candidates/$jobId': {
      id: '/$slug/_layout/candidates/$jobId'
      path: '/candidates/$jobId'
      fullPath: '/$slug/candidates/$jobId'
      preLoaderRoute: typeof SlugLayoutCandidatesJobIdRouteRouteImport
      parentRoute: typeof SlugLayoutRouteRoute
    }
    '/$slug/_layout/candidates/$jobId/': {
      id: '/$slug/_layout/candidates/$jobId/'
      path: '/'
      fullPath: '/$slug/candidates/$jobId/'
      preLoaderRoute: typeof SlugLayoutCandidatesJobIdIndexRouteImport
      parentRoute: typeof SlugLayoutCandidatesJobIdRouteRoute
    }
    '/$slug/_layout/candidates/$jobId/$candidateId': {
      id: '/$slug/_layout/candidates/$jobId/$candidateId'
      path: '/$candidateId'
      fullPath: '/$slug/candidates/$jobId/$candidateId'
      preLoaderRoute: typeof SlugLayoutCandidatesJobIdCandidateIdRouteImport
      parentRoute: typeof SlugLayoutCandidatesJobIdRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface SlugLayoutJobsRouteRouteChildren {
  SlugLayoutJobsJobIdRouteRoute: typeof SlugLayoutJobsJobIdRouteRoute
  SlugLayoutJobsIndexRoute: typeof SlugLayoutJobsIndexRoute
}

const SlugLayoutJobsRouteRouteChildren: SlugLayoutJobsRouteRouteChildren = {
  SlugLayoutJobsJobIdRouteRoute: SlugLayoutJobsJobIdRouteRoute,
  SlugLayoutJobsIndexRoute: SlugLayoutJobsIndexRoute,
}

const SlugLayoutJobsRouteRouteWithChildren =
  SlugLayoutJobsRouteRoute._addFileChildren(SlugLayoutJobsRouteRouteChildren)

interface SlugLayoutCandidatesJobIdRouteRouteChildren {
  SlugLayoutCandidatesJobIdCandidateIdRoute: typeof SlugLayoutCandidatesJobIdCandidateIdRoute
  SlugLayoutCandidatesJobIdIndexRoute: typeof SlugLayoutCandidatesJobIdIndexRoute
}

const SlugLayoutCandidatesJobIdRouteRouteChildren: SlugLayoutCandidatesJobIdRouteRouteChildren =
  {
    SlugLayoutCandidatesJobIdCandidateIdRoute:
      SlugLayoutCandidatesJobIdCandidateIdRoute,
    SlugLayoutCandidatesJobIdIndexRoute: SlugLayoutCandidatesJobIdIndexRoute,
  }

const SlugLayoutCandidatesJobIdRouteRouteWithChildren =
  SlugLayoutCandidatesJobIdRouteRoute._addFileChildren(
    SlugLayoutCandidatesJobIdRouteRouteChildren,
  )

interface SlugLayoutRouteRouteChildren {
  SlugLayoutBillingRouteRoute: typeof SlugLayoutBillingRouteRoute
  SlugLayoutCategoriesRouteRoute: typeof SlugLayoutCategoriesRouteRoute
  SlugLayoutJobsRouteRoute: typeof SlugLayoutJobsRouteRouteWithChildren
  SlugLayoutOrganizationRouteRoute: typeof SlugLayoutOrganizationRouteRoute
  SlugLayoutTeamRouteRoute: typeof SlugLayoutTeamRouteRoute
  SlugLayoutIndexRoute: typeof SlugLayoutIndexRoute
  SlugLayoutCandidatesJobIdRouteRoute: typeof SlugLayoutCandidatesJobIdRouteRouteWithChildren
  SlugLayoutCandidatesIndexRoute: typeof SlugLayoutCandidatesIndexRoute
  SlugLayoutHiringStagesIndexRoute: typeof SlugLayoutHiringStagesIndexRoute
}

const SlugLayoutRouteRouteChildren: SlugLayoutRouteRouteChildren = {
  SlugLayoutBillingRouteRoute: SlugLayoutBillingRouteRoute,
  SlugLayoutCategoriesRouteRoute: SlugLayoutCategoriesRouteRoute,
  SlugLayoutJobsRouteRoute: SlugLayoutJobsRouteRouteWithChildren,
  SlugLayoutOrganizationRouteRoute: SlugLayoutOrganizationRouteRoute,
  SlugLayoutTeamRouteRoute: SlugLayoutTeamRouteRoute,
  SlugLayoutIndexRoute: SlugLayoutIndexRoute,
  SlugLayoutCandidatesJobIdRouteRoute:
    SlugLayoutCandidatesJobIdRouteRouteWithChildren,
  SlugLayoutCandidatesIndexRoute: SlugLayoutCandidatesIndexRoute,
  SlugLayoutHiringStagesIndexRoute: SlugLayoutHiringStagesIndexRoute,
}

const SlugLayoutRouteRouteWithChildren = SlugLayoutRouteRoute._addFileChildren(
  SlugLayoutRouteRouteChildren,
)

interface ViewSlugRouteRouteChildren {
  ViewSlugIndexRoute: typeof ViewSlugIndexRoute
  ViewSlugJobIdIndexRoute: typeof ViewSlugJobIdIndexRoute
}

const ViewSlugRouteRouteChildren: ViewSlugRouteRouteChildren = {
  ViewSlugIndexRoute: ViewSlugIndexRoute,
  ViewSlugJobIdIndexRoute: ViewSlugJobIdIndexRoute,
}

const ViewSlugRouteRouteWithChildren = ViewSlugRouteRoute._addFileChildren(
  ViewSlugRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  SlugLayoutRouteRoute: SlugLayoutRouteRouteWithChildren,
  ViewSlugRouteRoute: ViewSlugRouteRouteWithChildren,
  ViewIndexRoute: ViewIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
