/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardOrganizationsRouteRouteImport } from './routes/dashboard/organizations/route'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as DashboardOrgSlugLayoutRouteRouteImport } from './routes/dashboard/org/$slug/_layout/route'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardOrganizationsRouteRoute =
  DashboardOrganizationsRouteRouteImport.update({
    id: '/organizations',
    path: '/organizations',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardOrgSlugLayoutRouteRoute =
  DashboardOrgSlugLayoutRouteRouteImport.update({
    id: '/org/$slug/_layout',
    path: '/org/$slug',
    getParentRoute: () => DashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/organizations': typeof DashboardOrganizationsRouteRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/org/$slug': typeof DashboardOrgSlugLayoutRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/organizations': typeof DashboardOrganizationsRouteRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/org/$slug': typeof DashboardOrgSlugLayoutRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/organizations': typeof DashboardOrganizationsRouteRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/org/$slug/_layout': typeof DashboardOrgSlugLayoutRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/organizations'
    | '/api/auth/$'
    | '/dashboard/org/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/dashboard/organizations'
    | '/api/auth/$'
    | '/dashboard/org/$slug'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/organizations'
    | '/api/auth/$'
    | '/dashboard/org/$slug/_layout'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/organizations': {
      id: '/dashboard/organizations'
      path: '/organizations'
      fullPath: '/dashboard/organizations'
      preLoaderRoute: typeof DashboardOrganizationsRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/org/$slug/_layout': {
      id: '/dashboard/org/$slug/_layout'
      path: '/org/$slug'
      fullPath: '/dashboard/org/$slug'
      preLoaderRoute: typeof DashboardOrgSlugLayoutRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardOrganizationsRouteRoute: typeof DashboardOrganizationsRouteRoute
  DashboardOrgSlugLayoutRouteRoute: typeof DashboardOrgSlugLayoutRouteRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardOrganizationsRouteRoute: DashboardOrganizationsRouteRoute,
  DashboardOrgSlugLayoutRouteRoute: DashboardOrgSlugLayoutRouteRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
