/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as ViewSlugRouteRouteImport } from './routes/view/$slug/route'
import { Route as SlugLayoutRouteRouteImport } from './routes/$slug/_layout/route'
import { Route as SlugLayoutIndexRouteImport } from './routes/$slug/_layout/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as SlugLayoutJobsRouteRouteImport } from './routes/$slug/_layout/jobs/route'
import { Route as SlugLayoutApplicantsRouteRouteImport } from './routes/$slug/_layout/applicants/route'
import { Route as SlugLayoutJobsIndexRouteImport } from './routes/$slug/_layout/jobs/index'
import { Route as SlugLayoutJobsJobIdRouteRouteImport } from './routes/$slug/_layout/jobs/$jobId/route'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const ViewSlugRouteRoute = ViewSlugRouteRouteImport.update({
  id: '/view/$slug',
  path: '/view/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugLayoutRouteRoute = SlugLayoutRouteRouteImport.update({
  id: '/$slug/_layout',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugLayoutIndexRoute = SlugLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SlugLayoutRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugLayoutJobsRouteRoute = SlugLayoutJobsRouteRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => SlugLayoutRouteRoute,
} as any)
const SlugLayoutApplicantsRouteRoute =
  SlugLayoutApplicantsRouteRouteImport.update({
    id: '/applicants',
    path: '/applicants',
    getParentRoute: () => SlugLayoutRouteRoute,
  } as any)
const SlugLayoutJobsIndexRoute = SlugLayoutJobsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SlugLayoutJobsRouteRoute,
} as any)
const SlugLayoutJobsJobIdRouteRoute =
  SlugLayoutJobsJobIdRouteRouteImport.update({
    id: '/$jobId',
    path: '/$jobId',
    getParentRoute: () => SlugLayoutJobsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/$slug': typeof SlugLayoutRouteRouteWithChildren
  '/view/$slug': typeof ViewSlugRouteRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/$slug/applicants': typeof SlugLayoutApplicantsRouteRoute
  '/$slug/jobs': typeof SlugLayoutJobsRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/$slug/': typeof SlugLayoutIndexRoute
  '/$slug/jobs/$jobId': typeof SlugLayoutJobsJobIdRouteRoute
  '/$slug/jobs/': typeof SlugLayoutJobsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/view/$slug': typeof ViewSlugRouteRoute
  '/dashboard': typeof DashboardIndexRoute
  '/$slug/applicants': typeof SlugLayoutApplicantsRouteRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/$slug': typeof SlugLayoutIndexRoute
  '/$slug/jobs/$jobId': typeof SlugLayoutJobsJobIdRouteRoute
  '/$slug/jobs': typeof SlugLayoutJobsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/$slug/_layout': typeof SlugLayoutRouteRouteWithChildren
  '/view/$slug': typeof ViewSlugRouteRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/$slug/_layout/applicants': typeof SlugLayoutApplicantsRouteRoute
  '/$slug/_layout/jobs': typeof SlugLayoutJobsRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/$slug/_layout/': typeof SlugLayoutIndexRoute
  '/$slug/_layout/jobs/$jobId': typeof SlugLayoutJobsJobIdRouteRoute
  '/$slug/_layout/jobs/': typeof SlugLayoutJobsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/$slug'
    | '/view/$slug'
    | '/dashboard/'
    | '/$slug/applicants'
    | '/$slug/jobs'
    | '/api/auth/$'
    | '/$slug/'
    | '/$slug/jobs/$jobId'
    | '/$slug/jobs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/view/$slug'
    | '/dashboard'
    | '/$slug/applicants'
    | '/api/auth/$'
    | '/$slug'
    | '/$slug/jobs/$jobId'
    | '/$slug/jobs'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/$slug/_layout'
    | '/view/$slug'
    | '/dashboard/'
    | '/$slug/_layout/applicants'
    | '/$slug/_layout/jobs'
    | '/api/auth/$'
    | '/$slug/_layout/'
    | '/$slug/_layout/jobs/$jobId'
    | '/$slug/_layout/jobs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  SlugLayoutRouteRoute: typeof SlugLayoutRouteRouteWithChildren
  ViewSlugRouteRoute: typeof ViewSlugRouteRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/view/$slug': {
      id: '/view/$slug'
      path: '/view/$slug'
      fullPath: '/view/$slug'
      preLoaderRoute: typeof ViewSlugRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/_layout': {
      id: '/$slug/_layout'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/_layout/': {
      id: '/$slug/_layout/'
      path: '/'
      fullPath: '/$slug/'
      preLoaderRoute: typeof SlugLayoutIndexRouteImport
      parentRoute: typeof SlugLayoutRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/_layout/jobs': {
      id: '/$slug/_layout/jobs'
      path: '/jobs'
      fullPath: '/$slug/jobs'
      preLoaderRoute: typeof SlugLayoutJobsRouteRouteImport
      parentRoute: typeof SlugLayoutRouteRoute
    }
    '/$slug/_layout/applicants': {
      id: '/$slug/_layout/applicants'
      path: '/applicants'
      fullPath: '/$slug/applicants'
      preLoaderRoute: typeof SlugLayoutApplicantsRouteRouteImport
      parentRoute: typeof SlugLayoutRouteRoute
    }
    '/$slug/_layout/jobs/': {
      id: '/$slug/_layout/jobs/'
      path: '/'
      fullPath: '/$slug/jobs/'
      preLoaderRoute: typeof SlugLayoutJobsIndexRouteImport
      parentRoute: typeof SlugLayoutJobsRouteRoute
    }
    '/$slug/_layout/jobs/$jobId': {
      id: '/$slug/_layout/jobs/$jobId'
      path: '/$jobId'
      fullPath: '/$slug/jobs/$jobId'
      preLoaderRoute: typeof SlugLayoutJobsJobIdRouteRouteImport
      parentRoute: typeof SlugLayoutJobsRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface SlugLayoutJobsRouteRouteChildren {
  SlugLayoutJobsJobIdRouteRoute: typeof SlugLayoutJobsJobIdRouteRoute
  SlugLayoutJobsIndexRoute: typeof SlugLayoutJobsIndexRoute
}

const SlugLayoutJobsRouteRouteChildren: SlugLayoutJobsRouteRouteChildren = {
  SlugLayoutJobsJobIdRouteRoute: SlugLayoutJobsJobIdRouteRoute,
  SlugLayoutJobsIndexRoute: SlugLayoutJobsIndexRoute,
}

const SlugLayoutJobsRouteRouteWithChildren =
  SlugLayoutJobsRouteRoute._addFileChildren(SlugLayoutJobsRouteRouteChildren)

interface SlugLayoutRouteRouteChildren {
  SlugLayoutApplicantsRouteRoute: typeof SlugLayoutApplicantsRouteRoute
  SlugLayoutJobsRouteRoute: typeof SlugLayoutJobsRouteRouteWithChildren
  SlugLayoutIndexRoute: typeof SlugLayoutIndexRoute
}

const SlugLayoutRouteRouteChildren: SlugLayoutRouteRouteChildren = {
  SlugLayoutApplicantsRouteRoute: SlugLayoutApplicantsRouteRoute,
  SlugLayoutJobsRouteRoute: SlugLayoutJobsRouteRouteWithChildren,
  SlugLayoutIndexRoute: SlugLayoutIndexRoute,
}

const SlugLayoutRouteRouteWithChildren = SlugLayoutRouteRoute._addFileChildren(
  SlugLayoutRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  SlugLayoutRouteRoute: SlugLayoutRouteRouteWithChildren,
  ViewSlugRouteRoute: ViewSlugRouteRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
