import { Metadata } from "next"
import { Button } from "@/components/ui/button";
import { Loader2 } from "lucide-react";
import { Banknote } from "lucide-react";

export const metadata: Metadata = {
    title: "Loading",
    description: "Generated by create next app",
};

export default function Loading() {
    return (
        <> 
        <div className="flex justify-between items-center w-full">
        <h1 className="font-medium text-white text-3xl tracking-tight">Billing</h1>
        <Button size={"sm"} variant={"outline"} className=" bg-theme font-medium border border-dashed border-foreground/20 rounded-none">
        <Banknote className="size-4" />
        </Button>
        </div>
        <div className="w-full h-full items-center flex flex-col justify-center">
        <Loader2 className="size-8 animate-spin text-white" />
        </div>
      </>
    )
}