import { Metadata } from "next";
import { Button } from "@/components/ui/button";
import { Loader2 } from "lucide-react";
import CreateJob from "@/components/create-job";

export const metadata: Metadata = {
  title: "Loading",
  description: "Generated by create next app",
};

export default function Loading() {
  return (
    <>
      <div className="flex justify-between items-center w-full">
        <h1 className="font-extrabold text-3xl text-foreground tracking-tight">
          Jobs
        </h1>
        <CreateJob id="123" className="!cursor-default" />
      </div>
      <div className="w-full h-full items-center flex flex-col justify-center">
        <Loader2 className="size-8 animate-spin text-foreground" />
      </div>
    </>
  );
}
